import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import Navbar from "@/components/navbar"
import QueryProvider from "@/providers/queryProvider"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-gray-100")}>
        <QueryProvider>
          <div className="mx-auto max-w-3xl space-y-8 p-4">
            <Navbar />
            <main className="min-h-[80vh] rounded-md border border-gray-200 bg-white p-4">
              {children}
            </main>
          </div>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryProvider>
      </body>
    </html>
  )
}
